FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o prune ./cmd/prune

FROM alpine:3.22 AS final
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/prune .

ENTRYPOINT ["./prune"]
